export default [
    { id: 1, name: 'Tortilla' },
    { id: 2, name: 'Freeze-dried chicken' },
    { id: 3, name: 'Processed cheese' },
    { id: 4, name: 'Salsa' },
    { id: 5, name: 'Dried veggies' },
    { id: 6, name: 'Freeze-dried fruit' },
    { id: 7, name: 'Protein powder' },
    { id: 8, name: 'Powdered milk' },
    { id: 9, name: 'Freeze-dried macaroni' },
    { id: 10, name: 'Powdered cheese sauce mix' },
    { id: 11, name: 'Freeze-dried ham' },
    { id: 12, name: 'Pizza crust' },
    { id: 13, name: 'Tomato sauce' },
    { id: 14, name: 'Freeze-dried pepperoni' },
    { id: 15, name: 'Dehydrated lettuce' },
    { id: 16, name: 'Mixed greens' },
    { id: 17, name: 'Freeze-dried tofu' },
    { id: 18, name: 'Salad dressing' },
    { id: 19, name: 'Freeze-dried beef' },
    { id: 20, name: 'Freeze-dried potatoes' },
    { id: 21, name: 'Freeze-dried carrots' },
    { id: 22, name: 'Freeze-dried peas' },
    { id: 23, name: 'Dehydrated onions' },
    { id: 24, name: 'Dehydrated garlic' },
    { id: 25, name: 'Tomato paste' },
    { id: 26, name: 'Seasoning' },
    { id: 27, name: 'Pancake mix' },
    { id: 28, name: 'Maple syrup' },
    { id: 29, name: 'Freeze-dried ice cream' },
    { id: 30, name: 'Freeze-dried cereal' },
    { id: 31, name: 'Chicken' },  
    { id: 32, name: 'Processed Cheese' },  
    { id: 33, name: 'Salsa' },  
    { id: 34, name: 'Rice' },  
    { id: 35, name: 'Beans' },  
    { id: 36, name: 'Fish' }, 
    
  ]